@baseUrl=http://localhost:8080/postsT/list

### post list
GET {{baseUrl}}/

### post-regist
POST {{baseUrl}}/
Content-Type: application/json

{
  "title": "",
  "writer": "aa",
  "body": "body 1"
}

### post-regist
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "title - kim",
  "writer": "Kim",
  "body": "body - kim"
}

### post-info
GET {{baseUrl}}/1


### post-update
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "title": "title 1xxx",
  "body": "body 1xxx",
  "writer": "Hongxxx"
}

### post-remove
DELETE {{baseUrl}}/1
